swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /temperature:
    get:
      operationId: "temperature.read"
      tags:
        - "Temperature"
      summary: "The temperature data structure supported by the server application"
      description: "Read the list of temperature"
      responses:
        200:
          description: "Successful read temperature list operation"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "number"
                devicename:
                  type: "string"
                temp:
                  type: "number"
                timestamp:
                  type: "string"